# pyproject.toml
[tool.black]
line-length = 88
target-version = ['py310'] # Match your Python version
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''